name: 'Commit Status'
description: 'GitHub App to set Commit Status'
inputs:
  package:
    description: 'Name of the package to be deployed'
    required: false
  repository:
    description: 'Full repo name for example "ropensci/magick"'
    required: true
  ref:
    description: 'Hash of the commit to update'
    required: true
  buildlog:
    description: 'Link to the build logs'
    required: true
  universe:
    description: 'Name of the universe where packages were deployed to'
    required: true
  jobs:
    description: 'String with deployed packages to infer success'
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/commit-status:v3'
  env:
    PACKAGE: ${{ inputs.package }}
    REPOSITORY: ${{ inputs.repository }}
    REF: ${{ inputs.ref }}
    BUILDLOG: ${{ inputs.buildlog }}
    UNIVERSE: ${{ inputs.universe }}
    JOBS: ${{ inputs.jobs }}
