name: 'Commit Status'
description: 'GitHub App to set Commit Status'
inputs:
  repo:
    description: 'Full repo name for example "ropensci/magick"'
    required: true
  sha:
    description: 'Hash of the commit to update'
    required: true
  url:
    description: 'Link to the build logs'
    required: true
  universe:
    description: 'Name of the universe where packages were deployed to'
    required: true
  deployed_packages:
    description: 'String with deployed packages to infer success'
    required: false
  source_status:
    description: 'Success or failure of building source package vignettes'
    required: false
  docs_status:
    description: 'Success or failure of building pkgdown documentation'
    required: false
  ostype:
    description: 'The OS_type field in description'
    required: true
  package:
    description: 'Name of the package to be deployed'
    required: false
  has_app:
    description: 'If upstream has the app installed'
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/commit-status'
  env:
    REPO: ${{ inputs.repo }}
    SHA: ${{ inputs.sha }}
    BUILDLOG: ${{ inputs.url }}
    UNIVERSE: ${{ inputs.universe }}
    DEPLOYED_PACKAGES: ${{ inputs.deployed_packages }}
    SOURCE_STATUS: ${{ inputs.source_status }}
    DOCS_STATUS: ${{ inputs.docs_status }}
    OSTYPE: ${{ inputs.ostype }}
    PACKAGE: ${{ inputs.package }}
    HAS_APP: ${{ inputs.has_app }}
