name: 'Commit Status'
description: 'GitHub App to set Commit Status'
inputs:
  repo:
    description: 'Full repo name for example "ropensci/magick"'
    required: true
  sha:
    description: 'Hash of the commit to update'
    required: true
  url:
    description: 'Link to the build logs'
    required: true
  universe:
    description: 'Name of the universe where packages were deployed to'
    required: true
  deployed_packages:
    description: 'String with deployed packages to infer success'
    required: false
  source_status:
    description: 'Success or failure of building source package vignettes'
    required: false
runs:
  using: 'docker'
  image: 'docker://runiverse/commit-status'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.sha }}
    - ${{ inputs.url }}
    - ${{ inputs.universe }}
    - ${{ inputs.deployed_packages }}
    - ${{ inputs.source_status }}
